---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cieranhu/public_html/key-assist/
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp area.php $DEPLOYPATH
    - /bin/cp services.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
